- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.packages:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip




